---
title: "INFO0806 – Statistiques appliquées"
author: "FUZELLIER Maxence, BARBET Antoine"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 3 # three depths of headings (#, ## and ###)
editor_options: 
  chunk_output_type: inline
---

<style>
body {
  text-align: justify;
  font-size: 14pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(hrbrthemes)
library(plotly)
library(car)
```

```{r datasets, message=FALSE}
data <- read_csv("data/prestige.csv") %>% as_tibble()
data
```

```{r education}
education <- data %>% 
  ggplot(aes(x = education, y = prestige)) +
  geom_point() +
  geom_smooth(method = loess, color = "red", fill = "#69b3a2", se = T) +
  geom_smooth(method = lm, color = "blue", se = F) +
  theme_ipsum()

scatter_edu <- ggplotly(education)
scatter_edu
```

```{r income}
income <- data %>% 
  ggplot(aes(x = income, y = prestige)) +
  geom_point() +
  geom_smooth(method = loess, color = "red", fill = "#69b3a2", se = T) +
  geom_smooth(method = lm, color = "blue", se = F) +
  theme_ipsum()

scatter_inc <- ggplotly(income)
scatter_inc
```

```{r}
prest.lm1 <- lm(prestige~education, data = Prestige)
prest.lm1
```

```{r lagplot}
bacf <- acf(residuals(prest.lm1), plot = F)
bacfdf <- with(bacf, data.frame(lag, acf))
conf.level <- 0.95
ciline <- qnorm((1 - conf.level)/2)/sqrt(length(residuals(prest.lm1)))

lag_plot <- bacfdf %>%
  ggplot(aes(x = lag, y = acf)) +
  geom_hline(aes(yintercept = 0)) +
  geom_segment(aes(xend = lag, yend = 0)) +
  geom_hline(aes(yintercept = ciline), linetype = 3, color = 'darkblue') +     
  geom_hline(aes(yintercept = -ciline), linetype = 3, color = 'darkblue') +
  theme_ipsum()

lag_plot <- ggplotly(lag_plot, tooltip = c("lag", "acf"))
lag_plot
```


```{r durbinWatson_edu}
durbinWatsonTest(prest.lm1)
```

```{r qq_edu}
qq_edu <- prest.lm1 %>%
  ggplot(aes(sample = residuals(prest.lm1) / 10))+
  stat_qq() + stat_qq_line() +
  #theme_ipsum() +
  labs(x = "Theoretical Quantiles\nlm(prestige ~ education)", 
       y = "Standardized residuals")

#qq_edu <- ggplotly(qq_edu)
qq_edu
```

```{r shapiro_edu}
shapiro.test(residuals(prest.lm1))
```

```{r}
prest.lm2 <- lm(prestige~income, data = Prestige)
prest.lm2
```

```{r qq_inc}
qq_inc <- prest.lm2 %>%
  ggplot(aes(sample = residuals(prest.lm2) / 10))+
  stat_qq() + stat_qq_line() +
  #theme_ipsum() +
  labs(x = "Theoretical Quantiles\nlm(prestige ~ income)", 
       y = "Standardized residuals")

#qq_inc <- ggplotly(qq_inc)
qq_inc
```


```{r shapiro_inc}
shapiro.test(residuals(prest.lm2))
```

```{r}
plot(prest.lm1, 3)
```

```{r}
ncvTest(prest.lm1)
```

```{r}
plot(prest.lm1,1)
```

```{r}
summary(prest.lm1)
```

```{r}
confint(prest.lm1)
```

```{r}
influenceIndexPlot(prest.lm1)
```

```{r}
outlierTest(prest.lm1)
```

```{r}
prest.lm1bis <- lm(prestige~education, data=Prestige[-c(53,67),])
compareCoefs(prest.lm1 ,prest.lm1bis) 
```

```{r}
my_df <- data.frame(education=c(10.25))
predict(prest.lm1, newdata=my_df)
```

```{r}
predict(prest.lm1, newdata=my_df, interval="prediction")
predict(prest.lm1, newdata=my_df, interval="confidence")
```

```{r}
my_df <- data.frame(education=c(10.25, 11.25, 12.25))
predict(prest.lm1, newdata=my_df,interval="confidence")
```

```{r}
my_pres <- Prestige
my_pres$res <-residuals(prest.lm1)
head(my_pres)
```

```{r}
my_pres$fitted <-fitted(prest.lm1)
head(my_pres)
```

```{r}
head(predict(prest.lm1))
head(fitted(prest.lm1))
```

```{r}
vcov(prest.lm1)
```

```{r}
ggplot(Prestige, aes(y=prestige, x=education))+
  geom_point()+
  geom_smooth(colour="red", method="lm", fill="red") +
  ylab("Prestige")+
  xlab("education") +
  theme_classic()+
  annotate("text", x = 9, y = 80, label = "prestige = -10.73 + 5.36 * education\n (pval<0.001)")
```

```{r}
int_pred <- predict(prest.lm1, interval="prediction")
my_prest2 <-cbind(Prestige, int_pred)
head(my_prest2)
```

```{r}
ggplot(my_prest2, aes(y=prestige, x=education))+
  geom_point()+
  geom_smooth(colour="red", method="lm", fill="red") +
  geom_line(aes(y=lwr), color = "red", linetype = "dashed")+
  geom_line(aes(y=upr), color = "red", linetype = "dashed")+    
  ylab("Prestige")+
  xlab("education") +
  theme_classic()+
  annotate("text", x = 9, y = 80, label = "prestige = -10.73 + 5.36 * education\n (pval<0.001)")
```
